### ISSUE TITLE
xdmf issues

### ISSUE THREAD

**Issue by jack-kcl** [KVSlab/turtleFSI#16] opened 2022-10-13 18:45 UTC
Hi-  I've been having trouble opening the xdmf files the code generates from the simulations in Paraview. This is in contrast to the mesh files provided, which load up just fine. I suppose the h5 files are problematic in some way? Looking around the web, it seems to be a common issue for a lot of people. Would you be able to suggest a workaround or a suitable alternative format to use? Thank you.

**Comment by keiyamamo** [comment] 2022-10-14 09:10
Hi @jack-kcl

I have no problem opening xdmf files from the simulations in Paraview. Which version of paraview are you using?
Maybe could you provide your xdmf file so that I can test on my computer? 

Best,
Kei

**Comment by jack-kcl** [comment] 2022-10-14 19:37
Dear Kei,

Thank you so much for getting back to me quickly. I have tried this with Paraview 5.4.1 (Linux), 5.11.0-RC1 (Linux), and I think 5.10.1 on mac.
With the xdmf3readerS or T, loading this file results in an immediate crash. With the XDMF Reader, it reports an error and loads nothing.
These are identical symptoms to those reported in e.g. https://discourse.paraview.org/t/failure-to-read-xdmf-files-generated-by-fenics/4928

The files generated from a demo problem are attached. Thank you for your help.

Best wishes,
Jack
________________________________

**Comment by keiyamamo** [comment] 2022-10-14 20:07
HI @jack-kcl 

Maybe you forgot to attach the file? I can’t seem to find the attached files. 
Anyway, I use 5.10.1 on my Mac and never experienced such a problem... I usually select xdmf3readerS and that works fine for me. May I also ask which version of FEniCS you are using? I use 2019.1.0.

**Comment by jack-kcl** [comment] 2022-10-14 20:18
[displacement.zip](https://github.com/KVSlab/turtleFSI/files/9789754/displacement.zip)

Sorry about that! Should be attached this time. 

I have tried two different ways, first installing turtleFSI from conda,-forge so the fenics was automatically added and I think the version is 2019.1.0. I also tried explicitly installing that version first, then building turtleFSI from source after that and the outcomes were the same.

**Comment by keiyamamo** [comment] 2022-10-14 20:37
Hi @jack-kcl 

Yes, I can reproduce the problem. However, it’s very weird because I have no problem opening displacement.xdmf when I run the demo problem on my computer. 

Did you run the demo problem until the end of the simulation? If you stop the simulation before it finishes, that might cause the problem...

**Comment by jack-kcl** [comment] 2022-10-14 20:42
Yes I ran the demo until it finished, with no error. I suspected the parallel write might be causing the issue so I've tried forcing mpirun -n 1 but the problem didn't go away. There was another thread I found that pointed out that setting the "flush_output" to True will fix this, but I can see that monolithic.py is already doing it. Puzzling.

I think I might wipe everything and start from beginning again.  Can I ask you whether your fenics was built from source? Perhaps there's something going on with the binaries on conda-forge.

**Comment by keiyamamo** [comment] 2022-10-14 21:00
Yes, you are absolutely right. I saw the same thread but turtleFSI already has “flush_output” to be True. I think I used conda-forge and did not build from the source, but I’m not 100% sure as it was long time ago. 

Another option that might work is to replace `d_write` `v_write` `p_write` to `d_write_checkpoint` (and so on). 
This is the link for the line that you may want to change:   https://github.com/KVSlab/turtleFSI/blob/23d21198a49c37dc6795417336ec6839791d7729/turtleFSI/problems/__init__.py#L296
and the explanation for `write_checkpoint`: https://fenicsproject.org/olddocs/dolfin/2017.2.0/python/programmers-reference/cpp/io/XDMFFile.html#dolfin.cpp.io.XDMFFile.write_checkpoint

**Comment by keiyamamo** [comment] 2022-10-14 21:02
I’m not sure if this will solve the problem as I’m really not sure what’s causing the problem..

**Comment by jack-kcl** [comment] 2022-10-14 21:05
Thank you for the suggestion, I will try it and report back.

**Comment by Han10th** [comment] 2022-10-17 14:46
Hi, may I know if this problem is solved? I met the same issue.

**Comment by keiyamamo** [comment] 2022-10-17 20:27
Hi @Han10th 
I do not know yet if what I suggested worked out, and I can not really test it myself since the output I get from turtleFSI does not have any issues... Sorry I can not be any help at the moment.

**Comment by jack-kcl** [comment] 2022-10-18 13:00
Hi sorry I've had some deadlines. I was about to try out the write_checkpoint() however I remembered the code dumps out a Checkpoint folder already so I tried to load those files in and the same error occurred -- I figured there's no point modifying the code because I'd only be copying the checkpoint function anyway.

I'm also trying to reinstall fenics by building it from source, however, there seem to be something breaking.

@Han10th would you mind sharing the details of what you did to reinstall fenics and turtleFSI? Did you use conda, or some other route? As per importing in paraview, perhaps this link will be useful:
https://jorgensd.github.io/dolfinx-tutorial/chapter1/membrane_paraview.html#using-paraview-for-visualization

**Comment by Han10th** [comment] 2022-10-19 04:18
Thanks for the reference.

For solving the issue. I pip uninstall turtleFSI, and conda uninstall FEniCS, fenicstool.

Then, reinstall fenics by "conda install -c conda-forge fenics".
Then, download turtleFSI from source via "git clone ...." and "python setup.py -install" according to the document.

**Comment by Han10th** [comment] 2022-10-19 04:19
I use Ubuntu 18, BTW.

**Comment by keiyamamo** [comment] 2022-11-30 20:20
Hi @jack-kcl 
Not sure if you solved the problem, but it seems like the xdmf issue is now fixed in the latest conda. 
Please see here: https://fenicsproject.discourse.group/t/xdmf-file-causes-a-crash-but-pvd-files-work/9864/4?u=kei_yamamoto

**Comment by jack-kcl** [comment] 2022-11-30 20:31
Hi 
Thank you very much for following up on this issue! I had to build from source to make the issue go away, but I also found that the conda 2018 version didn't suffer from this issue. I guess now the latest legacy version will work too.

**Closed** 2022-11-30 20:32 UTC
